---
  - name: Update apt packages
    become: true
    apt:
      update_cache: yes

  - name: "Upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: Install prerequisites for Docker repository
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes
    
  - name: install docker and it's dependencies
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: start and enable docker daemon
    service:
      name: docker
      state: started
      enabled: yes

  - name: Install Docker Compose
    become: yes
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  
  - name: Change permissions of Docker Compose executable
    become: yes
    shell: chmod +x /usr/local/bin/docker-compose
  
  - name: Test Docker Compose installation
    shell: docker-compose --version
  
  - name: Install kubernetes
    become: yes
    shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  
  - name: Open kubectl permissions
    shell: chmod +x ./kubectl
  
  - name: Move kubectl bin
    become: yes
    shell: mv ./kubectl /usr/local/bin/kubectl

  - name: Check kubernetes version
    shell: kubectl version --client
