apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingapp
spec:
  selector:
    matchLabels:
      app: bookingapp
  replicas: 1
  template:
    metadata:
      labels:
        app: bookingapp
    spec:
      containers:
        - name: bookingapp
          image: juanvaes/bookingapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookingapp
  labels:
    name: bookingapp
spec:
  type: NodePort
  selector:
    app: bookingapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80