version: 2.1

jobs:
  setup-api:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - run:
          name: Setup API Project
          command: |
            ls -la
            make setup
            source venv/bin/activate
            make install
      - save_cache:
          key: api-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - venv/
  check-api-lint:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "requirements.txt" }}
            - api-dependencies
      - run:
          name: Lint Api
          command: |
            pwd
            ls -la
            make lint

workflows:
  default:
    jobs:
      - setup-api
      - check-api-lint:
          requires: [setup-api]