version: 2.1

jobs:
  setup-api:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - run:
          name: Setup API Project
          command: |
            ls -la
            cat Makefile
            make setup

workflows:
  default:
    jobs:
      - setup-api