---
  - name: Copy compiled files
    become: true
    unarchive:
      src:  /home/circleci/project/bookingapp.tar.gz
      dest: /home/ubuntu/
  
  - name: List directory to debug
    shell: |
      pwd
      ls -la
      ls -la /home/ubuntu/
      ls -la /home/ubuntu/bookingapp
      ls -la /home/ubuntu/bookingapp/project

  - name: Build Docker Image
    become: true
    shell: |
      cd /home/ubuntu/bookingapp/project
      ls -la
      cat .env
      docker build -t juanvaes/bookingapp .

  - name: Push Docker Image to Docker Hub
    shell: |
      docker login -u "{{ lookup('env', 'DOCKERHUB_USERNAME') }}" -p "{{ lookup('env', 'DOCKERHUB_PW') }}"
      docker tag bookingapp:latest juanvaes/bookingapp:latest
      docker push juanvaes/bookingapp
 

  - name: Run Minikube Cluster
    ignore_errors: yes
    shell: |
      sudo chmod +x ./bookingapp/project/run_cluster.sh
      ./bookingapp/project/run_cluster.sh

  - name: Deploying App in Kubernetes
    shell: |
      sudo chmod +x ./bookingapp/project/run_kubernets.sh
      ./bookingapp/project/run_kubernets.sh

