---
  - name: Build Docker Image
    shell: docker build -t juanvaes/bookingapp .

  - name: Push Docker Image to Docker Hub
    shell: docker login -u "{{ DOCKERHUB_USERNAME }}" -p "{{ DOCKERHUB_PW }}"