---
  - name: Copy compiled files
    become: true
    unarchive:
      src:  /home/circleci/project/bookingapp.tar.gz
      dest: /home/ubuntu/
  
  - name: List directory to debug
    shell: |
      pwd
      ls -la
      ls -la /home/ubuntu/
      ls -la /home/ubuntu/bookingapp
      ls -la /home/ubuntu/bookingapp/project

  - name: Build Docker Image
    become: true
    shell: |
      cd /home/ubuntu/bookingapp
      ls -la
      docker build -t juanvaes/bookingapp .

  - name: Push Docker Image to Docker Hub
    shell: docker login -u "{{ DOCKERHUB_USERNAME }}" -p "{{ DOCKERHUB_PW }}"