---
  - name: Copy compiled files
    become: true
    unarchive:
      src:  /home/circleci/project/bookingapp.tar.gz
      dest: /home/ubuntu/
  
  - name: List directory to debug
    shell: |
      pwd
      ls -la
      ls -la /home/ubuntu/
      ls -la /home/ubuntu/bookingapp
      ls -la /home/ubuntu/bookingapp/project

  - name: Build Docker Image
    become: true
    shell: |
      cd /home/ubuntu/bookingapp/project
      ls -la
      cat .env
      docker build -t juanvaes/bookingapp .

  - name: Push Docker Image to Docker Hub
    shell: |
      docker login -u "{{ lookup('env', 'DOCKERHUB_USERNAME') }}" -p "{{ lookup('env', 'DOCKERHUB_PW') }}"
      docker tag bookingapp:latest juanvaes/bookingapp:latest
      docker push juanvaes/bookingapp
 

  - name: Run the Docker Hub Container with Kubernetes
    become: true
    ignore_errors: yes
    shell: |
      cd /home/ubuntu/bookingapp/project
      echo "Initializing conntrack and socat..."
      apt-get install -y conntrack
      apt-get install -y socat
#echo "Initializing cluster..."
#minikube start --driver=none
#mkdir -p $HOME/.kube
#cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#chown $(id -u):$(id -g) $HOME/.kube/config
#kubectl apply -f $HOME/bookingapp/project/app-deployment.yml
#echo "List created pods"
#kubectl get po
#echo "List created service"
#kubectl get svc
#echo "Starting minikube bookingapp service"
#minikube service bookingapp
      
# minikube start --driver=none
# kubectl cluster-info
# kubectl get nodes

# echo "Running bookingapp..."
# kubectl run bookingapp --image=juanvaes/bookingapp:latest --port=80 --labels app=bookingapp
# sleep 5
# echo "Listing pods"
# kubectl get pods
# echo "Port Forwarding"
# kubectl port-forward bookingapp 5000:80
